FROM auto_ui_download:latest as download

###############################################################################
# Runtime
FROM python:3.10-slim as runtime
# SHELL ["/bin/bash", "-ceuxo", "pipefail"]
ENV ROOT=/install
ENV REPO_PATH=repositories
ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1 PIP_NO_CACHE_DIR=1
ENV HASH_gfp=8d2447a2d918f8eba5a4a01463fd48e45126a379
ENV HASH_cl=d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
ENV HASH_mlf=bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b

RUN apt-get update && apt install fonts-dejavu-core rsync git jq moreutils -y && apt-get clean

# install packages
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install \
    git+https://github.com/TencentARC/GFPGAN.git@${HASH_gfp} \
    git+https://github.com/openai/CLIP.git@${HASH_cl} \
    git+https://github.com/mlfoundations/open_clip.git@${HASH_mlf} \
    pyngrok opencv-python-headless transformers==4.24

COPY --from=download /download/ ${ROOT}
COPY --from=download /wheel.whl xformers-0.0.15-cp310-cp310-linux_x86_64.whl

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install xformers-0.0.15-cp310-cp310-linux_x86_64.whl && rm xformers-0.0.15-cp310-cp310-linux_x86_64.whl
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install \
    -r ${ROOT}/${REPO_PATH}/CodeFormer/requirements.txt \
    -r ${ROOT}/${REPO_PATH}/stable-diffusion-webui1/requirements_versions.txt \
    -r ${ROOT}/${REPO_PATH}/stable-diffusion-webui2/requirements_versions.txt

COPY containers/auto_ui/* /docker/
COPY --from=download /download/${REPO_PATH}/stable-diffusion-webui2/ ${ROOT}

RUN mv  ${ROOT}/style.css ${ROOT}/user.css && \
    sed -i 's/os.rename(tmpdir, target_dir)/shutil.move(tmpdir,target_dir)/' ${ROOT}/modules/ui_extensions.py