FROM auto_ui_install:latest as install
ENV ROOT=/install

COPY containers/auto_ui/* /docker/

WORKDIR ${ROOT}
ENV CLI_ARGS="--allow-code --medvram --xformers --enable-insecure-extension-access --api"
EXPOSE 7860
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD python3 -u webui.py --listen --port 7860 ${CLI_ARGS}
