apiVersion: v1
kind: PersistentVolume
metadata:
  name: stable-diffusion-host-path-pv
  labels:
    type: local
spec:
  storageClassName: stable-diffusion-storage
  # storageClassName: local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/joe/repos/stable_diffusion_playground/
  volumeMode: Filesystem
