apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-svc
  namespace: sd
spec:
  type: NodePort
  selector:
    app: sd
  ports:
  - protocol: TCP
    port: 7860
    targetPort: 7860
    nodePort: 30000