apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stable-diffusion-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
mountOptions:
  - hard
  - nfsvers=4.1
  - noatime
parameters:
  fstype: ext4
  readOnly: "false"
  volumeType: premium-ssd
